### ISSUE TITLE
Picture won’t show up.

### ISSUE THREAD

**Issue by Dominic8978** [Team-Fruit/EEWBot#13]
So at the end of a Report there would be a picture showing the area in the intensities but for some reason this won’t show up now probably because the bot is broken so when you have time can you please fix this problem?

**Comment by sjcl** [comment]
I have tried several times to fix this problem and I know it still occurs.
I'm going to start developing the next update soon, so I'll try to make further fixes then.

**Comment by sjcl** [comment]
This feature has now been removed but was fixed prior to v2.4.1.
