### ISSUE TITLE
EEw turns into garbage.

### ISSUE THREAD

**Issue by BellCocoa** [Team-Fruit/EEWBot#4]
Please start EEw by Windows! When eew help is carried out, it turns into garbage.
![image](https://user-images.githubusercontent.com/36551213/69483550-e9802380-0e6b-11ea-9d56-73db08fa3eeb.png)

**Comment by sjcl** [comment]
Is this a problem with the exe version?

**Comment by BellCocoa** [comment]
jar filing is being carried out by a command prompt in Windows10, but everything turns into garbage.

**Comment by sjcl** [comment]
Specify `-Dfile.encoding=UTF-8` as a Java command option.
I'll try to fix it when compiling from the next release, but this can be solved for the time being.

**Comment by BellCocoa** [comment]
Thank you very much.
